config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: "users/registrations",
  }
  root to: 'rooms#index'

  get 'users/index'
  get 'users/:id/profile', to: 'users#profile', as: 'user_profile'
  get 'users/:id/profile_edit', to: 'users#profile_edit', as: 'user_profile_edit'

  get 'rooms/index_current_user', to: 'rooms#index_current_user' , as: 'index_current_user'

  resources :users, only: [:show,:update]
  resources :rooms do
    collection do
     get 'search'
    end
    resources :reservations, only: [:create, :destroy]
  end

  get 'reservations/index'
  post 'reservations/:id/confirm' , to:  'reservations#confirm' , as: 'reservation_confirm'
  get 'reservations/:id/reserve_form', to: 'reservations#reserve_form', as: 'reservation_reserve_form'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :rooms
  has_many :reservations
  has_many :reservation_rooms, through: :reservations, source: :room

  validates :name, :email, :password, :password_confirmation, presence: true, on: :create

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable
  
         mount_uploader :image, ImageUploader
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :image, infomation])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show , :profile ,:profile_edit]
  
  def top
  end
  
  def index
  end

  def show
  end

  def profile
  end

  def profile_edit
  end

  def update
    @user = User.find(params[:id])
    if @user.update!(user_params)
      redirect_to user_profile_path(@user.id)
    else
      binding.pry
      render :profile_edit
    end
  end


  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :infomation ,:image)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/profile.html.erb
<h1 class="username"><%= @user.name %>さん</h1>

<div class="user_info_message_container">
  <div class="user_info_message">プロフィール</div>
  <div class="user_info_edit"><%= link_to "編集", user_profile_edit_path( @user.id ) ,class: 'user_info_edit_link' %></div>
</div>

<div class="user_info_wallpaper">

  <div class="user_info_contents">
    <table class="user_info_swiching">
      <tr>
        <td><%= link_to "アカウント", user_path( current_user.id ), class: 'user_info_swiching_contents3' %></td>
      </tr>
      <tr>
        <td><%= link_to "プロフィール", user_profile_path( @user.id ), class: 'user_info_swiching_contents4' %></td>
      </tr>
    </table>

    <table class="user_info_display">
      <tr>
        <td>画像<img src=<%= @user.image %> class = "icon_image"></td>
      </tr>
      <tr>
        <td>名前:<%= @user.name %></td>
      </tr>
      <tr>
        <td>自己紹介:<%= @user.infomation %></td>
      </tr>
    </table>
  </div>

</div>

app/views/users/profile_edit.html.erb
<h1 class="username"><%= @user.name %>さん</h1>

<div class="user_info_message_container">
  <div class="user_info_message_edit">プロフィール</div>
</div>

<div class="user_info_wallpaper">

  <div class="user_info_contents">
    <table class="user_info_swiching">
      <tr>
        <td><%= link_to "アカウント", user_path( current_user.id ), class: 'user_info_swiching_contents3' %></td>
      </tr>
      <tr>
        <td><%= link_to "プロフィール", user_profile_path( @user.id ), class: 'user_info_swiching_contents4' %></td>
      </tr>
    </table>

    <table class="user_info_display">
      <%= form_with model: @user do |f| %>
        <tr>
          <td>
           <img src=<%= @user.image %> class = "icon_image">
           <div class="field">
            <%= f.label :image %><br/>
            <%= f.file_field :image %>
           </div>
          </td>
        </tr>
        <tr>
          <td>
            <div class="field">
            <%= f.label :name %><br />
            <%= f.text_field :name %>
          </div>
          </td>
        </tr>
        <tr>
          <td>
            <div class="field">
            <%= f.label :infomation %><br />
            <%= f.text_field :infomation %>
            </div>
          </td>
        </tr>
        <tr>
          <td>
            <div class="actions">
              <%= f.submit "保存" %>
            </div>
          </td>
        </tr>
      <% end %>
    </table>
  </div>

</div>

app/views/users/show.html.erb
<h1 class="username"><%= @user.name %>さん</h1>

<div class="user_info_message_container">
  <div class="user_info_message">アカウント</div>
  <div class="user_info_edit"><%= link_to "編集", edit_user_registration_path(@user) ,class: 'user_info_edit_link' %></div>
</div>

<div class="user_info_wallpaper">

  <div class="user_info_contents">
    <table class="user_info_swiching">
      <tr>
      <td><%= link_to "アカウント", user_path( current_user.id ), class: 'user_info_swiching_contents1' %></td>
      </tr>
      <tr>
      <td><%= link_to "プロフィール", user_profile_path( @user.id ), class: 'user_info_swiching_contents2' %></td>
      </tr>
    </table>

    <table class="user_info_display">
      <tr>
      <td>メールアドレス:<%= @user.email %></td>
      </tr>
      <tr>
      <td>パスワード:************</td>
      </tr>
    </table>
  </div>

</div>

app/views/users/top.html.erb
<div>Hello</div>