config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: "users/registrations",
  }
  root to: 'rooms#index'

  get 'users/index'
  get 'users/:id/profile', to: 'users#profile', as: 'user_profile'
  get 'users/:id/profile_edit', to: 'users#profile_edit', as: 'user_profile_edit'

  get 'rooms/index_current_user', to: 'rooms#index_current_user' , as: 'index_current_user'

  resources :users, only: [:show,:update]
  resources :rooms do
    collection do
     get 'search'
    end
    resources :reservations, only: [:create, :destroy]
  end

  get 'reservations/index'
  post 'reservations/:id/confirm' , to:  'reservations#confirm' , as: 'reservation_confirm'
  get 'reservations/:id/reserve_form', to: 'reservations#reserve_form', as: 'reservation_reserve_form'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord

    belongs_to :user
    has_many :reservations
    has_many :reservation_users, through: :reservations, source: :user

    mount_uploader :room_image, ImageUploader

    validates :room_info, :room_price, :room_address , presence: true
    validates :room_price, numericality: { greater_than_or_equal_to: 1 }

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

    before_action :set_q, only: [:index, :search]

    def index
        @rooms = Room.all
    end

    def index_current_user
        @user = User.find_by(id: current_user.id)
        @rooms = @user.rooms
    end
  
    def show
        @room = Room.find(params[:id])
        @reservation = Reservation.new
    end
  
    def new
        @room = Room.new
    end
  
    def create
        @room = Room.new(room_params)
        @room.user_id = current_user.id
        if @room.save
            flash[:notice] = "施設を新規作成しました"
            redirect_to rooms_path
        else
            flash.now[:notice] = "施設の作成に失敗しました"
            render "new"
        end
    end
  
    def edit
    end
  
    def update
    end
  
    def destroy
    end

    def search
        @results = @q.result
    end
    

    private

    def room_params
        params.require(:room).permit(:room_name, :room_info, :room_image, :room_price , :room_address,)
    end

    def set_q
        @q = Room.ransack(params[:q])
    end

end

app/helpers/room_helper.rb
module RoomHelper
end

app/views/rooms/index.html.erb
<div class="search_form">
    <div class="form_contents">
        <div class="free_search">
            <div class="form_title">施設検索</div>
            <%= search_form_for @q, url: search_rooms_path do |f| %>
                <%= f.label :room_name_or_room_info_cont, 'フリーワード' %>
                <%= f.search_field :room_name_cont %>
                <%= f.label :room_address_cont, 'エリア' %>
                <%= f.search_field :room_address_cont %>
                <%= f.submit '検索' %>
            <% end %>
        </div>
        <div class="area_search">
            <div class="form_title">エリア検索</div>
            <%= search_form_for @q, url: search_rooms_path do |f| %>
                <%= f.radio_button :room_address_cont, '東京' %>東京
                <%= f.radio_button :room_address_cont, '大阪' %>大阪
                <%= f.radio_button :room_address_cont, '京都' %>京都
                <%= f.radio_button :room_address_cont, '札幌' %>札幌
                <br><%= f.submit '検索' %>
            <% end %> 
        </div>
    </div>
</div>

<%  @rooms.each_slice(3) do |room1,room2,room3| %>

    <div class="index_date_container">

        <% if room1 != nil %>
            <div class="index_date">

                <div class="room_image_container_index">
                    <% if room1.room_image.present? %>
                        <div class="room_image_index"><img src=<%= room1.room_image %> class = "room_image_display_index"></div>
                    <% else %>
                        <div class="room_image_index"><%= image_tag '/default_room_image.png' , class: "room_image_display_index" %></div>
                    <% end %>
                </div>

                <div class="room_show_info_index">
                    <div class="room_show_NamePrice_index">
                        <div class="room_name_index"><%= room1.room_name %></div>
                    </div>
                    <div class="room_address_index"><%= room1.room_address %></div>
                    <div class="room_evaluation_index"><%= "⭐️⭐️⭐️⭐️⭐️" %></div>
                    <div class="room_info_index"><%= room1.room_info %></div>
                    <div class="index_date_footer">
                        <div class="room_price_index">¥<%= room1.room_price %>〜</div>
                        <%= link_to "詳細を確認", room_path(room1.id), class: 'btn btn-default' %>
                    </div>
                </div>

            </div>
        <% end %>


        <% if room2 != nil %>
            <div class="index_date">

                <div class="room_image_container_index">
                    <% if room2.room_image.present? %>
                        <div class="room_image_index"><img src=<%= room2.room_image %> class = "room_image_display_index"></div>
                    <% else %>
                        <div class="room_image_index"><%= image_tag '/default_room_image.png' , class: "room_image_display_index" %></div>
                    <% end %>
                </div>

                <div class="room_show_info_index">
                    <div class="room_show_NamePrice_index">
                        <div class="room_name_index"><%= room2.room_name %></div>
                    </div>
                    <div class="room_address_index"><%= room2.room_address %></div>
                    <div class="room_evaluation_index"><%= "⭐️⭐️⭐️⭐️⭐️" %></div>
                    <div class="room_info_index"><%= room2.room_info %></div>
                    <div class="index_date_footer">
                        <div class="room_price_index">¥<%= room2.room_price %>〜</div>
                        <%= link_to "詳細を確認", room_path(room2.id), class: 'btn btn-default' %>
                    </div>
                </div>

            </div>
        <% end %>


        <% if room3 != nil %>
            <div class="index_date">

                <div class="room_image_container_index">
                    <% if room3.room_image.present? %>
                        <div class="room_image_index"><img src=<%= room3.room_image %> class = "room_image_display_index"></div>
                    <% else %>
                        <div class="room_image_index"><%= image_tag '/default_room_image.png' , class: "room_image_display_index" %></div>
                    <% end %>
                </div>

                <div class="room_show_info_index">
                    <div class="room_show_NamePrice_index">
                        <div class="room_name_index"><%= room3.room_name %></div>
                    </div>
                    <div class="room_address_index"><%= room3.room_address %></div>
                    <div class="room_evaluation_index"><%= "⭐️⭐️⭐️⭐️⭐️" %></div>
                    <div class="room_info_index"><%= room3.room_info %></div>
                    <div class="index_date_footer">
                        <div class="room_price_index">¥<%= room3.room_price %>〜</div>
                        <%= link_to "詳細を確認", room_path(room3.id), class: 'btn btn-default' %>
                    </div>
                </div>

            </div>
        <% end %>

    </div>


<% end %>

app/views/rooms/index_current_user.html.erb
<div class="top_message">登録済み施設一覧</div>

<table class="table_index_current_user">
    <tr>
        <th class="index_current_user_data">画像</th>
        <th class="index_current_user_data">施設名</th>
        <th class="index_current_user_data">紹介文</th>
        <th class="index_current_user_data">料金</th>
        <th class="index_current_user_data">作成日</th>
    </tr>
    <% @rooms.each do |room| %>
    <tr>
        <td class="index_current_user_data_image" >
            <% if room.room_image.present? %>
                <div class="room_image_index"><img src=<%= room.room_image %> class = "room_image_display_index_current_user"></div>
            <% else %>
                <div class="room_image_index"><%= image_tag '/default_room_image.png' , class: "room_image_display_index_current_user" %></div>
            <% end %>
        </td>
        <td class="index_current_user_data"><%= link_to "#{room.room_name}" , room_path(room.id) , class: "btn-default_date"%></td>
        <td class="index_current_user_data"><%= room.room_info %></td>
        <td class="index_current_user_data"><%= room.room_price %></td>
        <td class="index_current_user_data"><%= room.created_at.to_s(:calender) %></td>
    </tr>
    <% end %>
</table>

app/views/rooms/new.html.erb
<div class="rooms_new_wallpaper">

<div class="rooms_new_container">
 <div>*以下全て必須項目です / 値段は数値で記入*</div>
 <%= form_with model: @room do |f| %>

       <div class="field">
            <%= f.label :room_name , "施設名" ,class: "label" %><br/>
            <%= f.text_field :room_name %>
       </div>
      
        <div class="field">
            <%= f.label :room_info , "施設情報" ,class: "label" %><br />
            <%= f.text_area :room_info , class: 'form-control', size: "148x8" %>
        </div>
      
        <div class="field">
            <%= f.label :room_price , "値段" ,class: "label" %><br />
            <%= f.text_field :room_price %>
        </div>

        <div class="field">
            <%= f.label :room_address , "住所" ,class: "label" %><br />
            <%= f.text_field :room_address %>
        </div>

        <div class="field">
            <%= f.label :room_image , "施設画像" ,class: "label" %><br />
            <%= f.file_field :room_image %>
        </div>
      
        <div class="actions">
            <%= f.submit "保存" %>
        </div>

 <% end %>
        <div class="cansel">
            <%= link_to '戻る', :back , class: "back_button"%>
        </div>
</div>

</div>

app/views/rooms/search.html.erb
<div class="search_form">
    <div class="form_contents">
        <div class="free_search">
            <div class="form_title">施設検索</div>
            <%= search_form_for @q, url: search_rooms_path do |f| %>
                <%= f.label :room_name_or_room_info_cont, 'フリーワード' %>
                <%= f.search_field :room_name_cont %>
                <%= f.label :room_address_cont, 'エリア' %>
                <%= f.search_field :room_address_cont %>
                <%= f.submit '検索' %>
            <% end %>
        </div>
        <div class="area_search">
            <div class="form_title">エリア検索</div>
            <%= search_form_for @q, url: search_rooms_path do |f| %>
                <%= f.radio_button :room_address_cont, '東京' %>東京
                <%= f.radio_button :room_address_cont, '大阪' %>大阪
                <%= f.radio_button :room_address_cont, '京都' %>京都
                <%= f.radio_button :room_address_cont, '札幌' %>札幌
                <br><%= f.submit '検索' %>
            <% end %> 
        </div>
    </div>
</div>

<%  @results.each_slice(3) do |room1,room2,room3| %>

    <div class="index_date_container">

        <% if room1 != nil %>
            <div class="index_date">

                <div class="room_image_container_index">
                    <% if room1.room_image.present? %>
                        <div class="room_image_index"><img src=<%= room1.room_image %> class = "room_image_display_index"></div>
                    <% else %>
                        <div class="room_image_index"><%= image_tag '/default_room_image.png' , class: "room_image_display_index" %></div>
                    <% end %>
                </div>

                <div class="room_show_info_index">
                    <div class="room_show_NamePrice_index">
                        <div class="room_name_index"><%= room1.room_name %></div>
                    </div>
                    <div class="room_address_index"><%= room1.room_address %></div>
                    <div class="room_evaluation_index"><%= "⭐️⭐️⭐️⭐️⭐️" %></div>
                    <div class="room_info_index"><%= room1.room_info %></div>
                    <div class="index_date_footer">
                        <div class="room_price_index">¥<%= room1.room_price %>〜</div>
                        <%= link_to "詳細を確認", room_path(room1.id), class: 'btn btn-default' %>
                    </div>
                </div>

            </div>
        <% end %>


        <% if room2 != nil %>
            <div class="index_date">

                <div class="room_image_container_index">
                    <% if room2.room_image.present? %>
                        <div class="room_image_index"><img src=<%= room2.room_image %> class = "room_image_display_index"></div>
                    <% else %>
                        <div class="room_image_index"><%= image_tag '/default_room_image.png' , class: "room_image_display_index" %></div>
                    <% end %>
                </div>

                <div class="room_show_info_index">
                    <div class="room_show_NamePrice_index">
                        <div class="room_name_index"><%= room2.room_name %></div>
                    </div>
                    <div class="room_address_index"><%= room2.room_address %></div>
                    <div class="room_evaluation_index"><%= "⭐️⭐️⭐️⭐️⭐️" %></div>
                    <div class="room_info_index"><%= room2.room_info %></div>
                    <div class="index_date_footer">
                        <div class="room_price_index">¥<%= room2.room_price %>〜</div>
                        <%= link_to "詳細を確認", room_path(room2.id), class: 'btn btn-default' %>
                    </div>
                </div>

            </div>
        <% end %>


        <% if room3 != nil %>
            <div class="index_date">

                <div class="room_image_container_index">
                    <% if room3.room_image.present? %>
                        <div class="room_image_index"><img src=<%= room3.room_image %> class = "room_image_display_index"></div>
                    <% else %>
                        <div class="room_image_index"><%= image_tag '/default_room_image.png' , class: "room_image_display_index" %></div>
                    <% end %>
                </div>

                <div class="room_show_info_index">
                    <div class="room_show_NamePrice_index">
                        <div class="room_name_index"><%= room3.room_name %></div>
                    </div>
                    <div class="room_address_index"><%= room3.room_address %></div>
                    <div class="room_evaluation_index"><%= "⭐️⭐️⭐️⭐️⭐️" %></div>
                    <div class="room_info_index"><%= room3.room_info %></div>
                    <div class="index_date_footer">
                        <div class="room_price_index">¥<%= room3.room_price %>〜</div>
                        <%= link_to "詳細を確認", room_path(room3.id), class: 'btn btn-default' %>
                    </div>
                </div>

            </div>
        <% end %>

    </div>


<% end %>

app/views/rooms/show.html.erb
<div class="cansel_show">
    <%= link_to '←戻る', :back , class: "back_button"%>
</div>

<div class="room_show_wallpaper">

    <div class="room_image_container">
        <% if @room.room_image.present? %>
            <div class="room_image"><img src=<%= @room.room_image %> class = "room_image_display"></div>
        <% else %>
            <div class="room_image"><%= image_tag '/default_room_image.png' %></div>
        <% end %>
    </div>
    <div class="room_show_info">
        <div class="room_show_NamePrice">
            <div class="room_name"><%= @room.room_name %></div>
        </div>
        <div class="room_price">¥<%= @room.room_price %>〜</div>
        <div class="room_address"><%= @room.room_address %></div>
        <div class="room_evaluation"><%= "⭐️⭐️⭐️⭐️⭐️" %></div>
        <div class="room_info"><%= @room.room_info %></div>
        <div class="room_reserve">

            
            <%= form_with(model: [@room , @reservation] , local: true, url: reservation_confirm_path) do |f| %>
                <div class="field">
                    <%= f.label :start_day , "チェックイン" %><br/>
                    <%= f.date_field :start_day %>
                </div>
                <div class="field">
                    <%= f.label :last_day , "チェックアウト" %><br/>
                    <%= f.date_field :last_day %>
                </div>
                <div class="field">
                    <%= f.label :number_of_people , "予約人数" %><br/>
                    <%= f.number_field :number_of_people , min: 1 %>
                </div>
                <div class="room_reserve_submit_show">
                    <%= f.submit "予約する"%>
                </div>
            <% end %>

        </div>
    </div>

</div>